version: "3.8"
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server.py:/app/server.py
    env_file:
      - .env
  ibkr-cpapi:
    build:
      context: ib-cpapi
      dockerfile: Dockerfile
    volumes:
      - ./log:/log
    restart: always
    ports:
      - "5000:5000"
