version: "3.8"
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server.py:/app/server.py
    env_file:
      - .env
  ibkr-cpapi:
    restart: always
    image: dradrian/ibportal:latest
    ports:
      - "9999:5000"
